title: SLSA
description: Supply-chain Levels for Software Artifacts
copyright_html: Copyright 2021 The Linux Foundation<br>under the terms of the <a href="https://github.com/slsa-framework/slsa/blob/main/LICENSE">Apache License 2.0</a>
repository: slsa-framework/slsa
header_pages:
  - index.md
  - specifications.md
  - use-cases.md
  - get-started.md
  - community.md
exclude:
  - README.md
# collections:
#   specifications:
#     layout: specifications
#     sort_by: order
#     output: true
google_analytics: G-VNK063J3QF
theme: minima
permalink: :path/:basename
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["autolink", "strikethrough", "table", "tagfilter"]
titles_from_headings:
  strip_title: true
include: ["docs/node_modules/tailwindcss"]
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-sitemap
  - jekyll-seo-tag
  # Mandatory GitHub Pages plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-toc
specs_version: "v0.2"
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "_specifications"
    values:
      folder: true