title: SLSA • Supply-chain Levels for Software Artifacts
description: Safeguarding artifact integrity across any software supply chain
copyright_html: Copyright 2021 The Linux Foundation<br>under the terms of the <a href="https://github.com/slsa-framework/slsa/blob/main/LICENSE">Apache License 2.0</a>
repository: slsa-framework/slsa
logo: https://github.com/slsa-framework/slsa/blob/main/resources/assets/logo/SLSA-logo.svg
url: https://slsa.dev
collections:
  spec:
    layout: specifications
    output: true
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - vendor/
google_analytics: G-VNK063J3QF
theme: minima
permalink: :path/:basename
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["autolink", "strikethrough", "table", "tagfilter"]
titles_from_headings:
  strip_title: true
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-sitemap
  - jekyll-seo-tag
  # Mandatory GitHub Pages plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
# WARNING: Remember to update _data/nav.yml as well.
spec_versions: ['v0.1']
current_spec_version: "v0.1"
provenance_versions: ['v0.1', "v0.2"]
current_provenance_version: "v0.2"
relative_links:
  collections: true
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "_spec"
    values:
      folder: true
